## Test cases file

In [1]:
# Test cases file

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from urllib import request
module_url = f"https://drive.google.com/uc?export=view&id=18y6hLv2bqAyJsIXwVCty58lF0u7yimVq"
module_url2 = f"https://drive.google.com/uc?export=view&id=1gjxxRtNf3hz9-DE-s9nJ_LBOgBXj2x1-"
module_name = 'commentary.txt'
name2 = 'superheros.csv'
with request.urlopen(module_url) as f, open(module_name,'w') as outf, request.urlopen(module_url2) as f2, open(name2,'w') as outf2:
  a = f.read()
  outf.write(a.decode('utf-8'))
  a2 = f2.read()
  outf2.write(a2.decode('utf-8'))

## The Coursework library

In [3]:
import c12345678 as test1
# replace c12345678 with your own .py library file name
# make sure this .py file is uploaded to Colab and can be seen in the folder left ;)

['Dimitrios Giannoulis hand-balls.', 'Armando Broja fouls Illan Meslier.', 'Armando Broja hand-balls.', 'Ciaran Clark fouls Moussa Sissoko.', 'Conor Gallagher hand-balls.', 'Atento, balón centrado, defensa expulsa, falla gol. ¡Huele injusticia! Juega, ¡Koke lanza! ¡Marca Ñíguez!', 'Asistencia, balón, cuelga, derecha, espectador, fútbol gol. Hinchada, júbilo, Koke, lanza, marca, Ñíguez.', 'Acierta, balón, centro, da, espectacular, falta gol. Hinchada, ¡increíble! Juego, Koke, lanza, marca, Ñíguez.', 'Atención, balón, centrado, dirección, esquina, falla gol. Hinchada, inquieta, juega, Koke, levanta, marca, Ñíguez.', 'Atento, balón, centro, defensa, extraño, fútbol gol. Hinchada, inquieta, juega, Koke, lanza, marca, Ñíguez.', 'Acierta, balón, controla, dispara, espectacular, falta gol. Hinchada, inquieta, juega, Koke, lanza, marca, Ñíguez.', 'Atención, balón, centrado, dirección, esquina, falla gol. Hinchada, increíble, juega, Koke, lanza, marca, Ñíguez.']
Dimitrios Giannoulis hand-balls.

## Question 1 Test cases

In [4]:
# Question 1 - Test case 1
print('Question 1 Test case 1 output is', test1.all_rounder([1, 7, 5], 'append', [3, 4, 2, 104]))
# Question 1 Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]

Question 1 Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]


In [5]:
# Question 1 - Test case 2
print('Question 1 Test case 2 output is', test1.all_rounder([99, 97, 90], 'append', [-99, -80, -79, -69]))
# Question 1 Test case 2 output is [99, 97, 90], 'append', [-99, -80, -79, -69]))

Question 1 Test case 2 output is [99, 97, 90, [-99, -80, -79, -69]]


In [6]:
# Question 1 - Test case 3
print('Test case 3 output is', test1.all_rounder('#', 'join', '(\'Jack\', \'Mahmut\')'))
# Question 1 Test case 3 output is Jack#Mahmut

Test case 3 output is Jack#Mahmut


In [7]:
# Question 1 - Test case 4
print('Question 1 Test case 4 output is', test1.all_rounder('&', 'join', '(\'Marry\', \'Caroline\')'))
# Question 1 Test case 4 output is Marry&Caroline

Question 1 Test case 4 output is Marry&Caroline


## Question 2 Test cases

In [8]:
# Question 2 - Test case 1
a0 = np.asarray([[1,2],[-9, 4]])
b0 = np.asarray([[3,4,5,6],[1,1,0,-5]])
print('Question 2 Test case 1 output is\n', test1.padded_broadcasting(np.add, a0, b0, -100))
# Question 2 Test case 1 output is
# [[   4.    6.  -95.  -94.]
# [  -8.    5. -100. -105.]]

Question 2 Test case 1 output is
 [[   4    6  -95  -94]
 [  -8    5 -100 -105]]


In [9]:
# Question 2 - Test case 2
a1 = np.asarray([[34,57],[-91, 43]])
b1 = np.asarray([[33,42,51,67],[12,13,20,-15]])
print('Question 2 Test case 2 output is\n', test1.padded_broadcasting(np.add, a1, b1, -1000))
# Question 2 Test case 2 output is
# [[   67    99  -949  -933]
#  [  -79    56  -980 -1015]]

Question 2 Test case 2 output is
 [[   67    99  -949  -933]
 [  -79    56  -980 -1015]]


In [10]:
# Question 2 - Test case 3
a2 = np.asarray([[4,7],[1, 4],[2, 4]])
b2 = np.asarray([[3,2,1,7,9],[2,1,0,-5,1]])
print('Question 2 Test case 3 output is\n', test1.padded_broadcasting(np.add, a2, b2, -1))
# Question 2 Test case 3 output is
# [[ 7  9  0  6  8]
# [ 3  5 -1 -6  0]
# [ 1  3 -2 -2 -2]]

Question 2 Test case 3 output is
 [[ 7  9  0  6  8]
 [ 3  5 -1 -6  0]
 [ 1  3 -2 -2 -2]]


In [11]:
# Question 2 - Quality check case
print(test1.padded_broadcasting.__doc__)
#    Definition:
#
#    Input:
#
#    Output:


    Definition:
    Input:
        :param func: function name
        :param a: value of a
        :param b: value of b
        :param pad: padding value
    Output:
        :return: result
    


## Question 3 Test cases

In [12]:
# Question 3 - Test case 1
print('Question 3 Test case 1 output is', test1.txtanalyser('commentary.txt', 'RED-CARD!', np.mean, 'find'))
# Question 3 Test case 1 output is 59.8

Question 3 Test case 1 output is 59.8


In [13]:
# Question 3 - Test case 2
print('Question 3 Test case 2 output is', test1.txtanalyser('commentary.txt', 'GOOOOOAAL!', np.mean, 'find'))
# Question 3 Test case 2 output is 51.69597069597069

Question 3 Test case 2 output is 51.69597069597069


In [14]:
# Question 3 - Test case 3
print('Question 3 Test case 3 output is',test1.txtanalyser('commentary.txt', 'Ball possession: Tottenham: 44%, Liverpool: 56%.', np.mean, 'find'))
# Question 3 Test case 3 output is 97.0

Question 3 Test case 3 output is 97.0


In [15]:
# Question 3 - Test case 4
print('Question 3 Test case 4 output is', test1.txtanalyser('commentary.txt', 'GOOOOOAAL!', np.log, 'count'))
# Question 3 Test case 4 output is 241.0

Question 3 Test case 4 output is 241.0


In [16]:
# Question 3 - Test case 5
print('Question 3 Test case 5 output is', test1.txtanalyser('commentary.txt', 'RED-CARD!', np.log, 'count'))
# Question 3 Test case 5 output is 5.0

Question 3 Test case 5 output is 5.0


In [17]:
# Question 3 - Test case 6
print('Question 3 Test case 6 output is', test1.txtanalyser('commentary.txt', '56%.', np.log, 'count'))
# Question 3 Test case 6 output is 48.0

Question 3 Test case 6 output is 48.0


## Question 4 Test cases

In [18]:
# Question 4 - Test case 1
res = test1.find_alphabetical_order('commentary.txt', check_ties=True)
print(res[0])
# Dimitrios Giannoulis hand-balls.

Dimitrios Giannoulis hand-balls.


In [19]:
# Question 4 - res value questions
print(test1.find_alphabetical_order('commentary.txt', check_ties=True))

['Dimitrios Giannoulis hand-balls.', 'Armando Broja fouls Illan Meslier.', 'Armando Broja hand-balls.', 'Ciaran Clark fouls Moussa Sissoko.', 'Conor Gallagher hand-balls.', 'Atento, balón centrado, defensa expulsa, falla gol. ¡Huele injusticia! Juega, ¡Koke lanza! ¡Marca Ñíguez!', 'Asistencia, balón, cuelga, derecha, espectador, fútbol gol. Hinchada, júbilo, Koke, lanza, marca, Ñíguez.', 'Acierta, balón, centro, da, espectacular, falta gol. Hinchada, ¡increíble! Juego, Koke, lanza, marca, Ñíguez.', 'Atención, balón, centrado, dirección, esquina, falla gol. Hinchada, inquieta, juega, Koke, levanta, marca, Ñíguez.', 'Atento, balón, centro, defensa, extraño, fútbol gol. Hinchada, inquieta, juega, Koke, lanza, marca, Ñíguez.', 'Acierta, balón, controla, dispara, espectacular, falta gol. Hinchada, inquieta, juega, Koke, lanza, marca, Ñíguez.', 'Atención, balón, centrado, dirección, esquina, falla gol. Hinchada, increíble, juega, Koke, lanza, marca, Ñíguez.']


In [20]:
# Question 4 - Commentary languages (1 Mark): How many English comments did we find:
# My answer is : There are 5 English comments

In [21]:
# Question 4 - Name 3 footballers (1 Mark): Name 3 footballers that appear in comments:
# My answer is : 1. Dimitris Giannoulis 2. Armando Broja 3. Illan Meslier

## Question 5 Test cases

In [22]:
# Question 5 - Test cases
a,b,c,d = test1.pd_query()

In [23]:
# Question 5 - Test Query Question 1
print(a)

                 Name Alignment  Intelligence  Strength  Speed  Durability  \
198    Doctor Strange      good           100        10     12          84   
311         JJ Powell      good            88        10      8          10   
384  Mister Fantastic      good           100        10     18          70   
440       Professor X      good           100         8     12          14   
606      Yellowjacket      good            88        10     12          28   

     Power  Combat  Total  
198    100      60    366  
311     14      10    140  
384     32      64    294  
440     90      32    256  
606     12      14    164  


In [24]:
# Question 5 - Test Query Question 2
print(b)

Intelligence     88.0
Strength         80.0
Speed            67.0
Durability      120.0
Power           100.0
Combat           90.0
Total           545.0
dtype: float64


In [25]:
# Question 5 - Test Query Question 3
print(c)

Alignment
good    214.990741
bad     247.212121
Name: Total, dtype: float64


In [26]:
# Question 5 - Test Query Question 4
print(d)

    index               Name Alignment  Intelligence  Strength  Speed  \
0       5            Abraxas       bad            88       100     83   
1      16              Amazo       bad            75       100    100   
2      26       Anti-Monitor       bad            88        90     38   
3      28         Anti-Venom       NaN            75        60     65   
4      29         Apocalypse       bad           100       100     33   
5      82            Bizarro   neutral            75        95    100   
6      84         Black Adam       bad            88       100     92   
7     122           Brainiac       bad           100        28     63   
8     138     Captain Marvel      good           100       100     67   
9     171    Cyborg Superman       bad            75        93     92   
10    180           Darkseid       bad            88       100     23   
11    191          Destroyer       bad            50        95     58   
12    201           Doomsday       bad            8

In [27]:
print(d['Name'])

0               Abraxas
1                 Amazo
2          Anti-Monitor
3            Anti-Venom
4            Apocalypse
5               Bizarro
6            Black Adam
7              Brainiac
8        Captain Marvel
9       Cyborg Superman
10             Darkseid
11            Destroyer
12             Doomsday
13         Doppelganger
14             Dormammu
15        Fallen One II
16                Faora
17             Galactus
18          General Zod
19                 Goku
20                 Hulk
21             Hyperion
22            Jean Grey
23           Juggernaut
24                Magus
25    Martian Manhunter
26                Match
27                 Nova
28            Onslaught
29              Phoenix
30           Power Girl
31             Red Hulk
32             She-Hulk
33        Silver Surfer
34             Stardust
35             Superboy
36       Superboy-Prime
37            Supergirl
38             Superman
39               Thanos
40                 Thor
41          War 